tap "homebrew/bundle"
brew "mas"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "karabiner-elements"
cask "keka"
cask "linearmouse"
cask "livebook"
cask "mullvad-browser"
cask "postgres-unofficial"
cask "setapp"
cask "visual-studio-code"
cask "warp"
mas "WireGuard", id: 1451685025
