version: "3"

includes:
  brew:
    taskfile: ./taskfiles/brew.yaml
    aliases: [b]

  chezmoi:
    taskfile: ./taskfiles/chezmoi.yaml
    aliases: [c]

  nix:
    taskfile: ./taskfiles/nix.yaml
    aliases: [n]

  vscode:
    taskfile: ./taskfiles/vscode.yaml
    aliases: [v]

  yes24:
    taskfile: ./taskfiles/yes24.yaml
    aliases: [y]
